name: test_my_projects
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  easy_stepper: ^0.8.3
  pin_code_fields: ^8.0.1
  firebase_storage: ^11.6.5
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:

  uses-material-design: true


  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 700

    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/sf-pro-text/SFProText-Regular.ttf

    - family: MyProjectIcons
      fonts:
       - asset: assets/icons/MyProjectIcons.ttf
